/**
* Shell Lab
* CS 241 - Fall 2018
*/

/**
 * this file exists so that we can provide a main method which does a variety of
 * handy things.
 *
 * DO NOT EDIT THIS FILE!
 */

// entry point for student code
int shell(int argc, char **argv);
